In [7]:
import numpy as np

In [8]:
arr1 = np.arange(21)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
arr1[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
arr1[3::3]

array([ 3,  6,  9, 12, 15, 18])