In [1]:
import numpy as np

In [3]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
array2 = np.linalg.inv(array1)
array1.dot(array2)

array([[1., 0.],
       [0., 1.]])

In [5]:
#2. 運用上列array計算特徵值、特徵向量?
np.linalg.eigvals(array1)
np.linalg.eig(array1)

(array([13.,  2.]),
 array([[ 0.93632918, -0.70710678],
        [ 0.35112344,  0.70710678]]))

In [6]:
#3. 運用上列array計算SVD?
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))